name: Generate Pac-Man Animation (Fixed)

on:
  schedule: # Jalankan setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. CHECKOUT REPO (Wajib untuk menginisialisasi repo lokal)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. GENERATE PACMAN SVG (File disimpan di root, yaitu './')
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Tidak perlu output karena file disimpan di root secara default

      # 3. PUSH KE OUTPUT BRANCH (Perubahan Krusial di 'build_dir')
      - name: Push pacman.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          # KRUSIAL: Ubah build_dir menjadi root repositori (titik)
          # Ini memberitahu action untuk mengambil file dari mana pun Pac-Man menaruhnya.
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
